name: Build and Deploy Code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
        with:
          repository: RUPSARKA/flaskapi-example
      - name: Install python version 3.9.5
        uses: actions/setup-python@v3
        with:
           python-version: '3.9.5'
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest